### ISSUE TITLE
添加了火星地球检疫一小节

### ISSUE THREAD

**Issue by emptymalei** [InterImm/InterImmBook#101]
http://book.interimm.org/history/mars_immigration.html#id19

添加了一个公司 Berlin Pioneer

**Comment by unionx** [comment]
感觉可以加点 BioPunk 的内容

**Comment by emptymalei** [comment]
biopunk 是什么鬼？bioshock 那种类型么？

**Comment by unionx** [comment]
类似，火星基地的生物危机？哈哈哈

**Comment by LostAbaddon** [comment]
BioPunk不是生化朋克么，以生化危机这种类型为代表，讲生化技术特别是基因强化与筛选以及身体强化等等所带来的问题，当然因为是Punk，所以一般都带有针对生化技术公司或者政府的反叛这样的情节。
（Punk嘛，本就是反控制的。）

**Comment by unionx** [comment]
其实就是生物科技爱好者自己在家鼓捣啦，参见这本书 http://book.douban.com/subject/20647000/
