### ISSUE TITLE
建立一个用来放置火星相关数据的 repo 的讨论

### ISSUE THREAD

**Issue by emptymalei** [InterImm/InterImmBook#39]
我在收集火星计时方法的过程中，突然有了这样一个想法：

我们单独建立一个火星参数相关的 repo，用来放置火星的（当前）相关数据，以便以后使用和总结。然后做成 json 数据格式，可以作为api 来用。

想讨论一下值不值得单独放出来。

---

Edit:

后续讨论应该转移到 [MarsData 的 issues 那边](https://github.com/InterImm/MarsData/issues) 。先关闭了。如有需要可以再开。

**Comment by emptymalei** [comment]
@unionx 我把这个 repo 改名了，现在叫做 InterImmData 因为我在放一些乱起八糟的东西。

**Comment by unionx** [comment]
好滴
