### ISSUE TITLE
火星城市及火星旅游图

### ISSUE THREAD

**Issue by emptymalei** [InterImm/InterImmBook#59]
我只有 GIMP，发现不好用，制作的没法好好对其什么的，源文件在此，如果觉得有问题可以更新这张图。

https://github.com/InterImm/InterImmBook/blob/master/resources/marsCities/marsCities.xcf

**Comment by emptymalei** [comment]
知乎上的一个问答[以后的火星旅游有哪些景点值得一去？](http://www.zhihu.com/question/25250799)

在想要不要用我们的官号发一个回答。

**Comment by emptymalei** [comment]
已回答：http://www.zhihu.com/question/25250799/answer/38091153

**Comment by ProtossProbe** [comment]
@emptymalei 赞爆了！

**Comment by styra** [comment]
@emptymalei 好棒！感觉可以用来扩充现有页面～～

**Comment by emptymalei** [comment]
话说可以制作太阳系旅游手册么……

不过要制作的话赶紧也就是堆砌现有的维基百科之类的相关内容。所以如果真的要弄顶多就是列表，然后加上相关链接吧。直接搬运的意义赶紧不大。

------
话说你们见过穷游旅游锦囊的 PDF 版么？制作的可好了。

**Comment by ProtossProbe** [comment]
@emptymalei 要不先试着做做火星旅游手册？

**Comment by emptymalei** [comment]
@ProtossProbe 可以试试啊。我们这周圆桌上可以讨论一下什么的。

反正我目前的想法是，即便做的话，也只能做一个非常骨架的东西，细节什么的，觉得没有必要做很多细节。

**Comment by emptymalei** [comment]
要是穷游能随便添加条目而且奇怪的内容不被删就好了2333 那样我就去添加火星的条目。

**Comment by emptymalei** [comment]
我错了，真的有火星：http://place.qyer.com/mars/

**Comment by unionx** [comment]
不如我们把这个地方占领了吧哈哈哈哈

**Comment by emptymalei** [comment]
在穷游建立了一个相册，不知道会不会被删
http://www.qyer.com/pictrip/5554584/album_2759485

**Comment by emptymalei** [comment]
啊哈哈，在穷游添加了火星描述竟然通过审核了。http://place.qyer.com/mars/ctyprofile/#cate_261777
