### ISSUE TITLE
【通知啦】万有青年养成计划入围通知

### ISSUE THREAD

**Issue by emptymalei** [InterImm/InterImmBook#66]
- [x] 修改帖子类型和名字
- [x] 宣传标语： 明确地告诉大家你要做什么，控制在20字之内，比如《创作10首“吐槽科学”歌，录制专辑》、《去嘉兴学习钢雕，分享作品创作过程》这样，这会有助于网友快速理解项目并进行投票哦，当然我们会一起建议合适的标题的~接下来我可能会通过邮件、原帖评论给你的计划提建议。
- [ ] 修改、细化您的计划（在原帖内修改）

以下是果壳发来的入围通知：

您可以去掉原先计划贴中的【申请】字样啦！修改为【入围计划】，同时修改帖子类别标签为【入围计划】（帖子发完之后是可以再编辑的，编辑的过程中可以修改这些信息）
您需要一个用于宣传的简短标题，明确地告诉大家你要做什么，控制在20字之内，比如《创作10首“吐槽科学”歌，录制专辑》、《去嘉兴学习钢雕，分享作品创作过程》这样，这会有助于网友快速理解项目并进行投票哦，当然我们会一起建议合适的标题的~接下来我可能会通过邮件、原帖评论给你的计划提建议。
终选评比会要求更多细节，请适当修改、细化您的计划（在原帖内修改），我们建议包含以下几点：
一些与您计划主题相关的背景知识，比如如果和医学相关，那么要介绍一下您做的这个会涉及哪些方面，参考过哪些资料；又或者您所做的计划，目前在国内国外的前景。建议给500字以内的篇幅，不宜过长，讲究深入浅出，能让普通人看懂。参考1 （打开此贴往下拉，背景介绍部分） 参考2（【什么叫做阿卡贝拉】部分）
最终成果是什么。如果是实体物品，那么放一张概念图是最好不过的；如果要做的是类似出版物的东西或者撰写系列帖子，建议给出大致提纲。参考1（打开此贴往下拉，小书图解教程图和教程视频部分） 参考2（手册设计部分）
一份时间表，时间最好是半年以内。建议对计划进行适当量化，可以设置一些小目标，写出一个分步实施的时间表。这可以便于我们评判计划的可行性。如果您的计划明显超过这个时间，一是细化目标，不要过于庞大，二是考虑尽可能地仔细规划时间，稍长于这个时间也是可以的。参考1（打开此贴往下拉，实施计划部分） 参考2（打开此贴往下拉，计划时间表部分）
一份大致预算及构成（以及预算超出资助金部分要如何解决，一般我们的资助不超过5000元）。这会直接反映计划的可执行性和您的规划能力。
一些能增加网友和评委给你投票的信心值的内容，比如介绍自己有过相关的经验经历、专业背景、在这个领域中所做过的努力、作品展示啦之类的~
以往的入围计划帖供参考：入围计划1，入围计划2，入围计划3，入围计划4
提供更方便联系到您的方式，比如QQ、微信等，请按照要求填写在下方的确认回执。
提供您的快递收件地址（恩，入围都有礼品相送！非大陆地区，请给我们一个国内可以接收快递的地址......）
我们即将修改万有青年养成计划专区页面为投票页面，开启之前，会给您两天对计划进行完善、修改的时间。我们计划在本周六开启投票专区，所以在此之前请抓紧时间咯~可能已经有网友在评论中对您的计划提出了意见建议，可以好好思考一下是否采纳，适当的时候予以回复。投票开启之后可以为计划拉票，但最终还是由评委评选，投票仅作一部分参考作用，请把更多精力放在计划质量本身~
投票环节：1月10日开启投票页面，1月19日10:00截止投票，我们会综合计划贴的质量、投票情况、问答质量进行评选，并以最快速度通知最终入选选手。如果有延迟，我们会公开通报给大家。
接下来一段时间,果壳网会将您的计划公布于果壳网站内、微博、豆瓣、微信、人人等渠道，帮助大家获得更多支持。届时也会有大量的提问，请积极互动，解答问题、疑虑，最重要的，这可以帮助你完善对你计划的阐述方式。

------

我这里 8 号（我们周四那天，北京时间大概是周四夜晚和周五早上那段时间）有考试，这个考试对我很重要，比较焦虑。所以如果你们有人有时间的话，能否先按照要求改一下呢？

**Comment by ProtossProbe** [comment]
我今天回去改一下

**Comment by emptymalei** [comment]
我看了一下宣传标语这个似乎可以直接用现在的帖子题目的。科学地设想未来星际殖民——星际移民局计划

-------

但是关于帖子的内容，我认为还不够平易近人。需要一些比较有趣的甚至卖萌的简单的介绍。我明天晚上会试着写写，你们什么想法也来说说？

**Comment by emptymalei** [comment]
我添加了一些开头的内容：http://www.guokr.com/post/651000/
主要是防止我们一开始说的太严肃导致没人看得下去。

**Comment by styra** [comment]
我觉得我们是不是把网站截（若干）个图插到文中，有图好说话？不知道点开网站的人有多大比例哎。
（另外我的浏览器(chrome@ubuntu)上，马斯克的那个视频不能原地播放，得跳到b站才能打开。）

**Comment by ProtossProbe** [comment]
感觉帖子内容已经相当全面了。暂时想不到有什么需要添加的内容......
