### ISSUE TITLE
太空探索路线图

### ISSUE THREAD

**Issue by emptymalei** [InterImm/InterImmBook#67]
内容更新到了 [wiki这里](https://github.com/InterImm/InterImmBook/wiki/%E7%81%AB%E6%98%9F%E6%AE%96%E6%B0%91)，以后相关内容就不再更新这个 issue 了。

--------

http://spaceexp.ihmc.us/resource/1J205X95J-1KWHJ9F-2167?fscreen=true

搜资料时候看到这个。

以及维基百科的火星探测器的 landing sites

http://upload.wikimedia.org/wikipedia/commons/transcoded/9/9d/Mars_Landing_Sites.ogv/Mars_Landing_Sites.ogv.480p.webm

-----

Mars Foundation 的计划，包括第一个基地，后面的建设技术等等。
http://www.marsfoundation.org/our-mission/
![image](https://cloud.githubusercontent.com/assets/663798/5694189/0a396ff6-9904-11e4-8ad8-ac7d60a68125.png)

他们有个 Hillside Settlement，选址是在水手大峡谷里面的一个叫做Candor Chasma的中间的某个地方
![image](https://cloud.githubusercontent.com/assets/663798/5694223/ed3cc350-9906-11e4-942c-1702a0eec0fd.png)
这里是一堆图片 http://www.marsfoundation.org/hillside-settlement/

![image](https://cloud.githubusercontent.com/assets/663798/5694242/19f98620-9908-11e4-98ab-ca31fe91acdd.png)

------------

火星基地技术问题：

http://www.marsfoundation.org/projects/technology-focus/

**Comment by unionx** [comment]
下面这个图好棒，哈哈哈哈
