### ISSUE TITLE
发现月球有块这样的奇异的地方

### ISSUE THREAD

**Issue by emptymalei** [InterImm/InterImmBook#74]
Google Earth Pro 免费了，我就升级了一下。顺便看了一眼月球然后发现这个地方：

![image](https://cloud.githubusercontent.com/assets/663798/6840654/7590a4a4-d342-11e4-9cb8-d150b854bd07.png)

Edit:

一些解释 http://www.guokr.com/post/671646/

**Comment by ProtossProbe** [comment]
有什么特别之处么。。。？

**Comment by emptymalei** [comment]
月球没有流水侵蚀没有地质活动，怎么形成这样的地形呢？

**Comment by styra** [comment]
岩浆？
外星人的飞机场！

**Comment by emptymalei** [comment]
update:

好吧，我写了个帖子结果被扔到果壳首页了，然后一些人去解释了：http://www.guokr.com/post/671646/

我觉得撞击坑熔岩这个解释比较好接受哎。
