### ISSUE TITLE
ExploreMars 2015 Summit

### ISSUE THREAD

**Issue by emptymalei** [InterImm/InterImmBook#79]
http://livestream.com/viewnow/exploremars2015?origin=stream_live&mixpanel_id=fab511223f83-073f428a7-43681f0a-2ee000-fab511224029e&acc_id=8664043&medium=email

不知道 livestream 有没有被墙。

-----

开场主持人提到了下面这两个日期：
2033-10-06 
2035-12-26 （这个圣诞节……）
是人类登上火星的日期。原因是这两个日期正好可以通过霍曼轨道到达火星……好吧我突然意识到我们并没有考虑这个因素。
2027-01-06 的轨道 http://www.wolframalpha.com/input/?i=mars+orbit+on+Jan+6+2027
2027-07-22 的火星地球轨道：http://www.wolframalpha.com/input/?i=mars+orbit+on+july+22+2027

霍曼转移的周期的话，是这么算的

t_H = \frac{T_e}{2}  \sqrt{ \frac{1}{8} ( r_1+r_2 )^3/R_e^3 } 

这样算下来，最节省的霍曼轨道去火星是 1.15 年的时间（http://www.wolframalpha.com/input/?i=Sqrt%5B%283.48%29%5E3%2F8%5D%2F2）。我们的设定是半年，算一下的话，不可能是霍曼轨道了。（http://www.wolframalpha.com/input/?i=Solve+Sqrt%5B%282.48%2Bx%29%5E3%2F8%5D%2F2+%3D%3D+0.5）

Cassie 的演讲里面提到了一个这样的机构：
International Framework for Planetary Protection

来避免对于其它地方（Mars, Europa, Enceladus）的污染，更重要的是要保护地球不受伤害。

另外，其中一个人提到了，Mars One 在跟马丁公司买火星探测器，想要先做一次重复 Pheonix 之类的探测。

**Comment by ProtossProbe** [comment]
当时我是考虑过发射窗口和轨道了的，我记得火星的发射窗口是两年多一点有一个，推出来 2027 年一月就在窗口附近。 飞行半年多是参考了一般探测器 6～8 月就能抵达火星，估计也不是走的严格的霍曼转移轨道。
原来看过一本载人登火方案的书籍，在登火轨道的选择上并不是说能量最省就最好，还要权衡由于航行时间过长遭受的辐射等等因素。

再加上设定里的方案是在近地轨道上组合一个飞船，所以燃料方面应该是足够的，所以当时设定的时候航行时间是六个月。

**Comment by ProtossProbe** [comment]
我局不是也已经有了检疫站了么。

**Comment by emptymalei** [comment]
@ProtossProbe 我瞧了一眼他们计划的两个日期，果然也并不是真的 Hohmann 轨道。看起来轨道跟我们的差不多。

好的那就没问题了。
