### ISSUE TITLE
Elon Musk 的火星计划

### ISSUE THREAD

**Issue by emptymalei** [InterImm/InterImmBook#84]
[在这里](http://mp.weixin.qq.com/s?__biz=MzA3MzI4MjgzMw==&mid=209221723&idx=1&sn=860d5a71b205355898b3852d75a7f9c5&scene=2&srcid=5fIpMzeJ3slDVWxN5Rv1&from=timeline&isappinstalled=0#rd)

我大致翻了一下，虽然不知道是怎么写成的，但是看起来还挺有道理。

> 1. 自然会有一大批顾客排队等着他们的服务——他们当前已经积压了50个发射计划，总价值超过50亿美元。他们竭尽所能的增加产量，短期目标是一年制造出40架猎鹰9号。 Musk相信，几年内SpaceX的发射成本将降到行业平均水平的十分之一，并且将接管全球商业太空发射的大多数业务。
> 2. 几个月前，Musk宣布SpaceX将在西雅图开始卫星生产工程，并在2030年前向近地轨道投放4000颗
> 3. Musk预计，把通往火星的车票定位50万美元可以为火星运送一百万人。他认为，50万不过是加州一栋中档房屋的价格，他补充道：「由于更多的人居住在更富裕的国家，他们完全可以支付这些钱完成一次火星旅行。」
![image](https://cloud.githubusercontent.com/assets/663798/9451820/2759c448-4a6e-11e5-9379-d3055113e58a.png)
> 4. 火星殖民运输机（以下简称MCT—译者注）MCT火箭的体型将十分巨大，动力也比现在SpaceX的动力引擎Raptor更强大，其太空舱至少可以承载100个人。所以，如果SpaceX能做到这些，Space X的成本至少可以降低到20倍。
> 5. 当专栏作家Ross Andersen（译者注：万古杂志副编辑，科技哲学领域作者）询问Musk关于越过火星到达太阳系其他空间的前景时，Musk乐观地回答：「如果我们能建立一个火星殖民地，我们几乎就能殖民整个太阳系，因为届时我们将拥有强大的经济实力来完善太空旅行。我们将到达木星的卫星，至少可以轻松的到达外部的几个卫星，或许会到达土星的卫星土卫六（也称泰坦星），以及其他小行星。一旦我们具备了那种经济实力，以及地球－火星的经济系统，我们将能触及整体太阳系。」

还看到这一段：

>中国是另一个能送人上太空的国家，而美国对中国的不爽更远甚于俄国，以致于中国宇航员被禁止在国际太空站的「酷小子俱乐部」旁遛弯。这就好比村里有三个实力不分伯仲的社会大哥，但很尴尬的是，其中两个大哥是有车一族，而没车的那位大哥每天得蹭车出去作威作福。对于这位没车大哥来说，真悲催。

略搞笑。

**Comment by unionx** [comment]
我们可以自己造一辆，嗯哼

**Comment by styra** [comment]
「如果我们能建立一个火星殖民地，我们几乎就能殖民整个太阳系，因为届时我们将拥有强大的经济实力来完善太空旅行。我们将到达木星的卫星，至少可以轻松的到达外部的几个卫星，或许会到达土星的卫星土卫六（也称泰坦星），以及其他小行星。一旦我们具备了那种经济实力，以及地球－火星的经济系统，我们将能触及整体太阳系。」
要是能实现的话，未来的工业规模得相当惊人，量级都大得很，才能支撑得起这样日常化的大规模太空活动。
