### ISSUE TITLE
NASA 今天的发布会只是说了有液态水

### ISSUE THREAD

**Issue by emptymalei** [InterImm/InterImmBook#88]
* http://www.nasa.gov/press-release/nasa-confirms-evidence-that-liquid-water-flows-on-today-s-mars

原因是看到了一些重复出现的像是流水造成的痕迹

![image](https://cloud.githubusercontent.com/assets/663798/10142606/f7c87cfa-65d0-11e5-8818-1f6603c08ade.png)

![image](https://cloud.githubusercontent.com/assets/663798/10142635/1987aff0-65d1-11e5-9d72-b897dd19ba9c.png)

**Comment by ProtossProbe** [comment]
对目前的设定内容有影响么……貌似没有。不过这次发现液态水，下一步是不是就该发现微生物或者微生物遗迹了，离设定的世界线越来越接近了呢。

**Comment by emptymalei** [comment]
是的呢，感觉发射 exomars 什么的地点的选择有了更好的依据了。

**Comment by styra** [comment]
这些水从哪里来的。
一定有渠道来新的水吧，不然存量肯定会消耗完。
有解释说是矿物潮解吸收的水，升温时释放。空气里能吸到那么多水啊……
