### ISSUE TITLE
MarsPolar Team

### ISSUE THREAD

**Issue by emptymalei** [InterImm/InterImmBook#99]
最近勾搭上了 MarsPolar 的创始人什么的，打听了一下情况。我总结在这里。

MarsPolar 干什么？

MarsPolar 跟 MarsOne 不同，这是一个更加开放，更加国际化的组织。他们第一阶段的目标是联合世界各地对火星探索感兴趣的人，然后把这些人组织起来，去实现火星上的一个居住点。

下面是几个关于 MarsPolar 的几个人物介绍：

* 创始人是： 24 岁的俄罗斯人 Arteum Yurievich Goncharov，加上 Gleb Osipov 和 Dmitro Kukhtaruk。他们都参加了 MarsOne 项目的候选人选拔，退出了 MarsOne，然后他们跟 Zubrin 讨论过之后，创立了 MarsPolar.
* Arteum Goncharov 是一个学 IT 的，有个学士学位，不过 15 岁就开始干 IT 了。
* Gleb Osipov 是个俄罗斯企业家和艺术指导。他在迪拜一家商业杂志工作。也参加过 MarsOne.
* Dmitro Kukhtaruk 是个 Ivano-Frankivsk 记者，同样参加过 MarsOne. 过去是学医学的。
* 他们里面还有其它人，比如 Roman Juranek 是个波兰企业家，之前是 MarsOne 的投资方。
* Alexander Trunkovsky 是个俄罗斯的自由建筑师。
* Hristina Panova 是个俄罗斯的设计师。
* 他们有一些其它的支持，比如澳大利亚火星协会的人，美国火星学会波兰分部的人等等。

Arteum Goncharov 说他们主要的想法是首先要连接全世界各地对实现人类登陆火星感兴趣的人。从科学起步，与从宣传起步是两种不同的思路，而他选择从媒体宣传起步。

**Comment by unionx** [comment]
咦，有什么进展嘛

**Comment by emptymalei** [comment]
就是勾搭到了创始人，然后问了些问题，最后觉得不靠谱。
